name: tests

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.8",   "plone60-py38"]
        - ["3.9",   "plone60-py39"]
        - ["3.10",   "plone60-py310"]
        - ["3.11",   "plone60-py311"]

    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config[0] }}-
          ${{ runner.os }}-pip-
    - name: Buildout cache
      uses: actions/cache@v3
      with:
        path: ~/.buildout/eggs
        key: ${{ runner.os }}-buildout-${{ matrix.config[1] }}-${{ hashFiles('setup.*', 'tox.ini', '*cfg') }}
        restore-keys: |
          ${{ runner.os }}-buildout-${{ matrix.config[1] }}-
          ${{ runner.os }}-buildout-
    - name: Setup Buildout to cache eggs
      run: |
        mkdir -p ~/.buildout/eggs
        echo "[buildout]" > ~/.buildout/default.cfg
        echo "eggs-directory = $(realpath ~/.buildout/eggs)" >> ~/.buildout/default.cfg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
